# Generated by Django 4.0.5 on 2023-05-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pictures'),
        ),
    ]
