# Generated by Django 4.0.5 on 2023-05-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_footer_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('faqs', models.TextField(help_text='Write your FAQs here.')),
                ('interests', models.TextField(help_text='Write about your interests here.')),
                ('skills', models.ManyToManyField(related_name='skills', to='portfolio.skill')),
            ],
        ),
    ]
